# GitHub Sponsors
github: [oven-sh]

# Open Collective
open_collective: bun

# Ko-fi
ko_fi: jarredsumner

# Patreon
patreon: jarredsumner

# Custom sponsorship URLs
custom: ["https://bun.sh/sponsor", "https://opencollective.com/bun"]
