# Bun configuration for Arsenal Lab
[test]
# Test organization
root = "./"

# Preload happy-dom to make browser APIs available in tests
preload = ["./test/setup.ts"]

# Coverage reporting
coverage = true
coverageThreshold = 80  # Realistic coverage goal
coverageSkipTestFiles = true  # Don't include test files in coverage

# Test reliability - randomize with fixed seed for reproducibility in CI
randomize = false  # Set to true in CI with --seed flag for catching order-dependent bugs

# Performance
timeout = 5000  # Default timeout per test in milliseconds
