# Bun configuration for Arsenal Lab
[test]
# Test organization
root = "./"

# Preload happy-dom to make browser APIs available in tests
preload = ["./test/setup.ts"]

# Coverage reporting
coverage = true
coverageThreshold = 80  # Realistic coverage goal
coverageSkipTestFiles = true  # Don't include test files in coverage
coverageReporter = ["text", "lcov"]  # Generate both console output and lcov for CI

# Test reliability - randomize with fixed seed for reproducibility in CI
# Bun v1.3: Use --randomize flag to find test dependencies
# Use --seed=<value> to reproduce specific test order
randomize = false  # Set to true in CI with --seed flag for catching order-dependent bugs

# Performance
timeout = 5000  # Default timeout per test in milliseconds

# Bun v1.3: Concurrent test configuration
# Note: concurrent tests have limitations:
# - expect.assertions() and expect.hasAssertions() not supported
# - toMatchSnapshot() not supported (use toMatchInlineSnapshot())
# - beforeAll/afterAll hooks run sequentially
