title: ""
labels: ["discussion"]
body: |
  ## General Discussion 💬

  Start a conversation about Bun, performance, JavaScript, or anything related to the ecosystem.

  ### Topic
  What would you like to discuss?

  ### Context
  Provide any background or context for your discussion topic.

  ### Questions or Points to Discuss
  - Point 1
  - Point 2
  - Point 3

  ### Related Resources
  - Links to relevant documentation, articles, or projects
  - Related discussions or issues

  ---
  **Discussion Guidelines:**
  - Be respectful and constructive
  - Stay on topic
  - Use appropriate labels
  - For questions, consider using the Q&A category instead
