name: 🐞 Bun System Gate Bug Report
description: Report a bug in Bun System Gate governance
title: "[BUG] "
labels: ["bug", "bun-gate"]
body:
  - type: checkboxes
    id: upgrade-check
    attributes:
      label: ✅ Upgrade Check
      description: Please confirm you've tried upgrading before reporting
      options:
        - label: I ran `bun upgrade` and the bug still exists
          required: true
        - label: I re-bootstrapped the latest gate script
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 🎯 What happened?
      description: Clear, concise description of the bug
      placeholder: "The gate blocked a valid package installation..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔍 Steps to reproduce
      description: Minimal code/commands to reproduce the issue
      placeholder: |
        1. Run `bun add some-package`
        2. Gate blocks with error X
        3. Expected behavior Y
      render: bash
    validations:
      required: true

  - type: textarea
    id: gate-output
    attributes:
      label: 🛡️ Gate Output
      description: Paste the full error message from gate.js
      placeholder: "❌ crypto: MD5 usage detected in patch..."
      render: text

  - type: textarea
    id: environment
    attributes:
      label: 💻 Environment
      description: Please provide your environment details
      placeholder: |
        - Bun version: `bun --version`
        - OS: `uname -mprs` (Linux/macOS) or PowerShell command (Windows)
        - Gate version: `git describe --tags --abbrev=0`
      render: markdown
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots (if visual)
      description: Add screenshots to help explain the issue

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional context
      description: Add any other context about the problem here
