name: ✨ Bun System Gate Feature Request
description: Suggest an improvement or new feature for Bun System Gate
title: "[FEATURE] "
labels: ["enhancement", "bun-gate"]
body:
  - type: textarea
    id: what-do-you-want
    attributes:
      label: 💡 What do you want?
      description: Clear, concise description of the feature you'd like
      placeholder: "Add support for custom security rules..."
    validations:
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: 🎯 Why is this needed?
      description: Explain the use-case, pain-point, or benefit
      placeholder: "Currently, developers can't... This would help because..."
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: 🛡️ Current workaround (if any)
      description: How do you work around this limitation today?
      placeholder: "We currently use manual code reviews..."

  - type: textarea
    id: suggested-solution
    attributes:
      label: 🚀 Suggested solution (if you have one)
      description: Optional - if you have ideas on how to implement this
      placeholder: "Add a new rule type that validates..."

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical for my organization
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional context
      description: Add any other context or examples
