
invariants:
  - id: no-eval
    name: No eval() / Function()
    severity: BLOCK
    script: rules/no-eval.ts
  - id: crypto-integrity
    name: Secure crypto only
    severity: BLOCK
    script: rules/crypto-integrity.ts
  - id: layer-boundary
    name: Layer boundary check
    severity: AMBER
    script: rules/layer-boundary.ts