name: CI with Patch Governance
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            patches/
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb', 'package.json', 'patches/**/*.patch') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ hashFiles('bun.lockb', 'patches/**/*.patch') }}
            ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run invariant validation
        run: bun run postinstall

      - name: Run patch audit
        run: bun run patch:audit

      - name: Run tension analysis
        run: bun run scripts/monitor-amber-edges.ts patches/example.patch example-package 2>/dev/null || true

      - name: Run tests
        run: bun test --coverage

      - name: Build project
        run: bun run build

      - name: Security audit
        run: bun audit

      - name: Performance validation
        run: bun run bench

  patch-governance:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'patch') || contains(github.event.head_commit.modified, 'patches/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Enhanced patch validation
        run: |
          bun install --frozen-lockfile
          bun run postinstall
          bun run patch:audit

      - name: Create governance report
        run: |
          echo "## Patch Governance Report" > governance-report.md
          echo "- ✅ Invariants validated" >> governance-report.md
          echo "- ✅ Security audit passed" >> governance-report.md
          echo "- ✅ Tension analysis completed" >> governance-report.md

      - name: Upload governance report
        uses: actions/upload-artifact@v3
        with:
          name: patch-governance-report
          path: governance-report.md